# Generated by Django 5.1.1 on 2024-10-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0003_remove_multiplechoicequestion_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlist',
            old_name='questionList_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='questionlist',
            old_name='questionList_name',
            new_name='name',
        ),
    ]
