# Generated by Django 5.1.1 on 2024-10-16 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0004_rename_questionlist_description_questionlist_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_choice_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('long_answer_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExtremeFormsApp.question')),
                ('questionList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExtremeFormsApp.questionlist')),
            ],
        ),
    ]
