# Generated by Django 5.1.1 on 2024-10-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
