# Generated by Django 5.1.1 on 2024-10-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0006_alter_questionlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
