# Generated by Django 5.1.1 on 2024-10-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0009_questionlist_shareable_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
    ]
