# Generated by Django 5.1.1 on 2024-10-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0010_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionList',
        ),
    ]
