# Generated by Django 5.1.1 on 2024-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0011_remove_answer_questionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionList',
            new_name='question_list',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='multiple_choice_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
