# Generated by Django 5.1.1 on 2024-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0012_rename_questionlist_question_question_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple_choice_options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
