# Generated by Django 5.1.1 on 2024-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtremeFormsApp', '0013_alter_question_multiple_choice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='form_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
